# Generated by Django 5.0.8 on 2024-10-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='SEO title for the tour', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True)),
                ('name', models.CharField(help_text='Title of the tour for users', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the tour name', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the tour for users')),
                ('departure_city', models.CharField(help_text='Departure city', max_length=100)),
                ('end_city', models.CharField(help_text='End city', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Number of days of the tour')),
                ('highlights', models.TextField(help_text='Please each highlight on a new line.')),
                ('included', models.TextField(help_text='Please each included item on a new line.')),
                ('small_image', models.ImageField(help_text='Small image for the tour', upload_to='tours/smaller/')),
                ('bigger_image', models.ImageField(help_text='Bigger image for the tour', upload_to='tours/bigger/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the gallery', upload_to='tours/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number (1, 2, 3, etc.)')),
                ('title', models.CharField(help_text='Title for this day', max_length=255)),
                ('description', models.TextField(help_text="Detailed description of the day's activities")),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='user.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='user.tourimage'),
        ),
    ]
