# Generated by Django 5.0.8 on 2024-10-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tour_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='briefly_points',
            field=models.TextField(blank=True, help_text='Briefly points for nights and locations, each on a new line.', null=True),
        ),
    ]
