# Generated by Django 5.0.8 on 2024-10-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tour_briefly_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.IntegerField(help_text='Action number (1, 2, 3, etc.)')),
                ('title', models.CharField(help_text='Title for this action', max_length=255)),
                ('description', models.TextField(help_text="Detailed description of the action's activities")),
            ],
        ),
        migrations.CreateModel(
            name='DayTripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the gallery', upload_to='daytrips/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DayTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='SEO title for the day trip', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True)),
                ('name', models.CharField(help_text='Title of the day trip for users', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the day trip name', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the day trip for users')),
                ('departure_city', models.CharField(help_text='Departure city', max_length=100)),
                ('end_city', models.CharField(help_text='End city', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('duration_hours', models.IntegerField(help_text='Number of hours for the day trip')),
                ('highlights', models.TextField(help_text='Each highlight on a new line.')),
                ('included', models.TextField(help_text='Each included item on a new line.')),
                ('small_image', models.ImageField(help_text='Small image for the day trip', upload_to='daytrips/smaller/')),
                ('bigger_image', models.ImageField(help_text='Bigger image for the day trip', upload_to='daytrips/bigger/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark the day trip as active or inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions', models.ManyToManyField(blank=True, related_name='daytrip_actions', to='user.actiondetail')),
                ('gallery_images', models.ManyToManyField(blank=True, to='user.daytripimage')),
            ],
        ),
        migrations.AddField(
            model_name='actiondetail',
            name='day_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_details', to='user.daytrip'),
        ),
    ]
