# Generated by Django 5.0.8 on 2024-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_actiondetail_daytripimage_daytrip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrip',
            name='is_best',
            field=models.BooleanField(default=True, help_text='Mark the day trip as best'),
        ),
    ]
