# Generated by Django 5.0.8 on 2024-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_daytrip_is_best'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='SEO title for the tour', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True)),
                ('name', models.CharField(help_text='Title of the tour for users', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the tour name', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the tour for users')),
                ('departure_city', models.CharField(help_text='Departure city', max_length=100)),
                ('end_city', models.CharField(help_text='End city', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Number of days of the tour')),
                ('highlights', models.TextField(help_text='Please each highlight on a new line.')),
                ('included', models.TextField(help_text='Please each included item on a new line.')),
                ('is_photography_tour', models.BooleanField(default=False, help_text='Mark the tour as a photography tour')),
                ('photography_tips', models.TextField(blank=True, help_text='Photography tips and recommendations', null=True)),
                ('recommended_equipment', models.TextField(blank=True, help_text='Suggested photography equipment for the tour', null=True)),
                ('small_image', models.ImageField(help_text='Small image for the tour', upload_to='tours/smaller/')),
                ('bigger_image', models.ImageField(help_text='Bigger image for the tour', upload_to='tours/bigger/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark the tour  as active or inactive')),
                ('is_best', models.BooleanField(default=True, help_text='Mark the tour as best')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='daytrip',
            name='briefly_points',
            field=models.TextField(blank=True, help_text='Briefly points for nights and locations, each on a new line.', null=True),
        ),
    ]
