# Generated by Django 5.0.8 on 2024-10-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_photographer_daytrip_briefly_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the gallery', upload_to='photographer/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='is_photography_tour',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='bigger_image',
            field=models.ImageField(help_text='Bigger image for the tour', upload_to='photographer/bigger/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark the photography tour as active or inactive'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='small_image',
            field=models.ImageField(help_text='Small image for the tour', upload_to='photographer/smaller/'),
        ),
        migrations.CreateModel(
            name='PhotographerDayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number (1, 2, 3, etc.)')),
                ('title', models.CharField(help_text='Title for this day', max_length=255)),
                ('description', models.TextField(help_text="Detailed description of the day's activities")),
                ('photographer_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='user.photographer')),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='day',
            field=models.ManyToManyField(blank=True, help_text='Day-by-day details of the tour', related_name='photographer_days', to='user.photographerdaydetail'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, help_text='Gallery images for the photography tour', to='user.photographerimage'),
        ),
    ]
