# Generated by Django 5.0.8 on 2024-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_photographerimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='SEO title for the camp', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True)),
                ('name', models.CharField(help_text='Camp name', max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the camp')),
                ('location', models.CharField(help_text='Location of the camp', max_length=100)),
                ('hero_image', models.ImageField(help_text='Hero image for the camp', upload_to='camps/hero/')),
                ('feature_1_icon', models.CharField(default='fas fa-gem', help_text='FontAwesome icon class for feature 1', max_length=50)),
                ('feature_1_title', models.CharField(help_text='Title for feature 1', max_length=100)),
                ('feature_1_description', models.TextField(blank=True, help_text='Description for feature 1')),
                ('feature_2_icon', models.CharField(default='fas fa-compass', help_text='FontAwesome icon class for feature 2', max_length=50)),
                ('feature_2_title', models.CharField(help_text='Title for feature 2', max_length=100)),
                ('feature_2_description', models.TextField(blank=True, help_text='Description for feature 2')),
                ('feature_3_icon', models.CharField(default='fas fa-utensils', help_text='FontAwesome icon class for feature 3', max_length=50)),
                ('feature_3_title', models.CharField(help_text='Title for feature 3', max_length=100)),
                ('feature_3_description', models.TextField(blank=True, help_text='Description for feature 3')),
                ('feature_4_icon', models.CharField(default='fas fa-spa', help_text='FontAwesome icon class for feature 4', max_length=50)),
                ('feature_4_title', models.CharField(help_text='Title for feature 4', max_length=100)),
                ('feature_4_description', models.TextField(blank=True, help_text='Description for feature 4')),
                ('suite_name', models.CharField(help_text='Name of the suite', max_length=100)),
                ('suite_description', models.TextField(help_text='Description of the suite')),
                ('suite_image', models.ImageField(help_text='Image of the suite', upload_to='camps/suites/')),
                ('suite_guest_capacity', models.CharField(help_text="Guest capacity description (e.g., 'Up to 2 guests')", max_length=50)),
                ('suite_bed_type', models.CharField(help_text="Bed type (e.g., 'King-size bed')", max_length=50)),
                ('suite_bathroom_type', models.CharField(help_text="Bathroom type (e.g., 'Ensuite bathroom with rain shower')", max_length=100)),
                ('suite_additional_features', models.TextField(blank=True, help_text="Comma-separated additional features (e.g., 'Private plunge pool')")),
                ('experience_1_title', models.CharField(help_text='Title for experience 1', max_length=100)),
                ('experience_1_description', models.TextField(help_text='Description for experience 1')),
                ('experience_1_image', models.ImageField(help_text='Image for experience 1', upload_to='camps/experiences/')),
                ('experience_2_title', models.CharField(help_text='Title for experience 2', max_length=100)),
                ('experience_2_description', models.TextField(help_text='Description for experience 2')),
                ('experience_2_image', models.ImageField(help_text='Image for experience 2', upload_to='camps/experiences/')),
                ('experience_3_title', models.CharField(help_text='Title for experience 3', max_length=100)),
                ('experience_3_description', models.TextField(help_text='Description for experience 3')),
                ('experience_3_image', models.ImageField(help_text='Image for experience 3', upload_to='camps/experiences/')),
                ('dining_image', models.ImageField(help_text='Background image for the dining section', upload_to='camps/dining/')),
                ('dining_highlight_1', models.CharField(help_text='First dining highlight', max_length=100)),
                ('dining_highlight_2', models.CharField(help_text='Second dining highlight', max_length=100)),
                ('dining_highlight_3', models.CharField(help_text='Third dining highlight', max_length=100)),
                ('dining_highlight_4', models.CharField(help_text='Fourth dining highlight', max_length=100)),
                ('booking_url', models.URLField(help_text='Link to booking page')),
            ],
        ),
    ]
