# Generated by Django 5.0.8 on 2024-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_camp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='booking_url',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='location',
        ),
        migrations.AddField(
            model_name='camp',
            name='heroDescription',
            field=models.CharField(default='Amazing desert Morocco Camp Experience', help_text='Location of the camp', max_length=100),
        ),
    ]
