# Generated by Django 5.0.8 on 2024-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_button_url',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
