# Generated by Django 5.0.8 on 2024-10-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_homepage_hero_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoroccoToursPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Morocco Tours - Discover Morocco Tours', max_length=255)),
                ('meta_description', models.TextField(default='Explore the beautiful landscapes of Morocco with our exciting and affordable tours.')),
                ('meta_keywords', models.TextField(default='Morocco tours, desert tours, Marrakech tours, Sahara desert trips, photography tours')),
                ('hero_title', models.CharField(default='Exciting and Affordable Morocco Desert Tours', max_length=255)),
                ('hero_paragraph', models.TextField(default='Create unforgettable memories with our Marrakech Desert Trips.')),
                ('hero_image', models.ImageField(default='default_hero.jpg', upload_to='morocco_tours/')),
                ('display_hero_button', models.BooleanField(default=True)),
                ('hero_button_text', models.CharField(default='Request Tour', max_length=50)),
                ('show_tours_section', models.BooleanField(default=True)),
                ('tours_section_title', models.CharField(default='Private Morocco Desert Tours', max_length=255)),
                ('show_strengths_section', models.BooleanField(default=True)),
                ('strengths_title', models.CharField(default='Our Strengths', max_length=255)),
                ('strength_items', models.JSONField(default=list)),
                ('show_steps_section', models.BooleanField(default=True)),
                ('steps_title', models.CharField(default='3 Steps To Your Dream Vacation', max_length=255)),
                ('step_1_title', models.CharField(default='Step 1: Fill in the form', max_length=255)),
                ('step_1_description', models.TextField(default='Submit your details to start your journey with us.')),
                ('step_1_image', models.ImageField(default='default_step1.jpg', upload_to='morocco_tours/')),
                ('step_2_title', models.CharField(default='Step 2: Receive Your Customizable Itinerary', max_length=255)),
                ('step_2_description', models.TextField(default='We will send you a detailed itinerary.')),
                ('step_2_image', models.ImageField(default='default_step2.jpg', upload_to='morocco_tours/')),
                ('step_3_title', models.CharField(default='Step 3: Pack Your Bags', max_length=255)),
                ('step_3_description', models.TextField(default='Get ready to explore Morocco!')),
                ('step_3_image', models.ImageField(default='default_step3.jpg', upload_to='morocco_tours/')),
            ],
        ),
    ]
