# Generated by Django 5.0.8 on 2024-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_moroccotourspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Custom Tours', max_length=255)),
                ('background_image', models.ImageField(default='default_strength.jpg', upload_to='morocco_tours/strengths/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_url',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_1_description',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_1_image',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_1_title',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_2_description',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_2_image',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_2_title',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_3_description',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_3_image',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='step_3_title',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='strength_items',
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='hero_button_url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_1_image',
            field=models.ImageField(default='default_service1.jpg', upload_to='morocco_tours/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_1_title',
            field=models.CharField(default='Officially Licensed Guides', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_2_image',
            field=models.ImageField(default='default_service2.jpg', upload_to='morocco_tours/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_2_title',
            field=models.CharField(default='Guided Walking Tour', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_3_image',
            field=models.ImageField(default='default_service3.jpg', upload_to='morocco_tours/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_3_title',
            field=models.CharField(default='Flexible Rescheduling', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='show_services',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='why_choose_image',
            field=models.ImageField(default='default_why_choose.jpg', upload_to='morocco_tours/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='why_choose_paragraphs',
            field=models.TextField(default='At Discover Morocco Tours, we organize exceptional tours across Morocco.\nExplore the Sahara Desert, the cities of Marrakech and Fes, and much more.\nContact us to plan your dream vacation with flexible itineraries and personalized services.'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='why_choose_title',
            field=models.CharField(default='Why Choose Our Private Tours?', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strengths',
            field=models.ManyToManyField(related_name='morocco_tours_pages', to='user.strengthitem'),
        ),
    ]
