# Generated by Django 5.0.8 on 2024-11-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_strengthitem_remove_homepage_hero_button_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='destinations',
            field=models.PositiveIntegerField(default=0, help_text='Number of destinations offered'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='happy_travelers',
            field=models.PositiveIntegerField(default=0, help_text='Total number of happy travelers'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='satisfaction_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage satisfaction rate, e.g., 95.5', max_digits=5),
        ),
        migrations.AddField(
            model_name='homepage',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Number of years of experience'),
        ),
    ]
