# Generated by Django 5.0.8 on 2024-11-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_homepage_satisfaction_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moroccotourspage',
            options={'verbose_name': 'Morocco Tours Page', 'verbose_name_plural': 'Morocco Tours Pages'},
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='service_1_image',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='service_1_title',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='service_2_image',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='service_2_title',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='service_3_image',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='service_3_title',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='show_services',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='moroccotourspage',
            name='why_choose_image',
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_description1',
            field=models.CharField(default='Officially Licensed Guides', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_description2',
            field=models.CharField(default='Guided Walking Tour', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_description3',
            field=models.CharField(default='Flexible Rescheduling', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_image1',
            field=models.ImageField(default='default_service1.jpg', upload_to='morocco_tours/services/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_image2',
            field=models.ImageField(default='default_service2.jpg', upload_to='morocco_tours/services/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_image3',
            field=models.ImageField(default='default_service3.jpg', upload_to='morocco_tours/services/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_title1',
            field=models.CharField(default='Licensed Guides', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_title2',
            field=models.CharField(default='Guided Walking Tour', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='service_title3',
            field=models.CharField(default='Flexible Rescheduling', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='show_services_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='show_why_choose_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='step1_description',
            field=models.TextField(default='Submit your details to start your journey with us.'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='step1_title',
            field=models.CharField(default='Step 1: Fill in the form', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='step2_description',
            field=models.TextField(default='We will send you a detailed itinerary.'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='step2_title',
            field=models.CharField(default='Step 2: Receive Your Customizable Itinerary', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='step3_description',
            field=models.TextField(default='Get ready to explore Morocco!'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='step3_title',
            field=models.CharField(default='Step 3: Pack Your Bags', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_image1',
            field=models.ImageField(default='default_strength1.jpg', upload_to='morocco_tours/strengths/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_image2',
            field=models.ImageField(default='default_strength2.jpg', upload_to='morocco_tours/strengths/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_image3',
            field=models.ImageField(default='default_strength3.jpg', upload_to='morocco_tours/strengths/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_image4',
            field=models.ImageField(default='default_strength4.jpg', upload_to='morocco_tours/strengths/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_image5',
            field=models.ImageField(default='default_strength5.jpg', upload_to='morocco_tours/strengths/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_image6',
            field=models.ImageField(default='default_strength6.jpg', upload_to='morocco_tours/strengths/'),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_title1',
            field=models.CharField(default='Custom Tours', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_title2',
            field=models.CharField(default='Photography Tours', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_title3',
            field=models.CharField(default='Licensed Guides', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_title4',
            field=models.CharField(default='Satisfaction Guaranteed', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_title5',
            field=models.CharField(default='Excellence', max_length=255),
        ),
        migrations.AddField(
            model_name='moroccotourspage',
            name='strength_title6',
            field=models.CharField(default='Trusted Experience', max_length=255),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='hero_button_url',
            field=models.URLField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='why_choose_paragraphs',
            field=models.TextField(default='At Discover Morocco Tours, we organize exceptional tours across Morocco.'),
        ),
    ]
