# Generated by Django 5.0.8 on 2024-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_moroccotourspage_why_choose_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moroccotourspage',
            name='steps_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='morocco_tours/'),
        ),
    ]
