# Generated by Django 5.0.8 on 2024-11-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_daytripspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytripspage',
            name='service_description1',
        ),
        migrations.RemoveField(
            model_name='daytripspage',
            name='service_description2',
        ),
        migrations.RemoveField(
            model_name='daytripspage',
            name='service_description3',
        ),
    ]
