# Generated by Django 5.0.8 on 2024-11-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_daytripspage_service_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerTourPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default="Photography Tours - Capture Morocco's Essence", max_length=255)),
                ('meta_description', models.TextField(default='Explore Morocco through the lens of your camera with our specially designed photography tours.')),
                ('meta_keywords', models.TextField(default='Morocco photography tours, Marrakech photography, Sahara photo tours')),
                ('hero_title', models.CharField(default="Photography Tours Capture Morocco's Essence", max_length=255)),
                ('hero_paragraph', models.TextField(default='Explore Morocco through the lens of your camera with our specially designed photography tours.')),
                ('hero_image_large', models.ImageField(default='default_large_hero.jpg', upload_to='photographer_tours/')),
                ('hero_image_medium', models.ImageField(default='default_medium_hero.jpg', upload_to='photographer_tours/')),
                ('hero_image_small', models.ImageField(default='default_small_hero.jpg', upload_to='photographer_tours/')),
                ('package_section_title', models.CharField(default='Photo Session Packages', max_length=255)),
                ('destination_section_title', models.CharField(default='Choose Your Destination, Let Us Do The Rest', max_length=255)),
                ('destination_paragraphs', models.TextField(default='At Discover Morocco Tours, we specialize in organizing exceptional tours across Morocco...')),
                ('image_description', models.ImageField(default='default_small_hero.jpg', upload_to='photographer_tours/')),
            ],
            options={
                'verbose_name': 'Photographer Tour Page',
                'verbose_name_plural': 'Photographer Tour Page',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=50)),
                ('retouched_photos', models.PositiveIntegerField()),
                ('color_corrected_photos', models.PositiveIntegerField()),
                ('editing_time', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='user.photographertourpage')),
            ],
        ),
    ]
