# Generated by Django 5.0.8 on 2024-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_photographertourpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographertourpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='package',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='original_price',
        ),
        migrations.AddField(
            model_name='package',
            name='current_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='old_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='editing_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
