# Generated by Django 5.0.8 on 2024-11-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_photographertourpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographertourpage',
            name='hero_button_text',
            field=models.CharField(default='Explore more', max_length=255),
        ),
    ]
