# Generated by Django 5.0.8 on 2024-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_photographertourpage_hero_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='current_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='old_price',
            field=models.PositiveIntegerField(),
        ),
    ]
