# Generated by Django 5.0.8 on 2024-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_package_current_price_alter_package_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesertCampPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Home - Discover Morocco Tours', max_length=255)),
                ('meta_description', models.TextField(default='Discover the beauty of Morocco with our exceptional tours and day trips. Contact us to plan your adventure today!')),
                ('meta_keywords', models.TextField(default='Morocco tours, day trips, desert tours, photography, luxury desert camp, Morocco travel')),
                ('hero_title', models.CharField(default='Exciting and Affordable Morocco Desert Tours', max_length=255)),
                ('hero_paragraph', models.TextField(default='Create unforgettable memories with our Marrakech Desert Trips.')),
                ('hero_image', models.ImageField(default='default_hero.jpg', upload_to='desert_camp/')),
                ('first_section_title', models.CharField(default='Luxury Desert camp', max_length=255)),
                ('first_section_text', models.TextField(default='At Discover Morocco Tours, we specialize in organizing exceptional tours across Morocco.')),
                ('first_section_image', models.ImageField(default='default_image2.jpg', upload_to='desert_camp/')),
                ('camps_section_title', models.CharField(default='OUR LODGES & TENTS', max_length=255)),
                ('small_info_title', models.CharField(default='Luxury Desert Camp', max_length=255)),
                ('small_info_text', models.TextField(default='At Discover Morocco Tours, we specialize in organizing exceptional tours across Morocco.')),
                ('small_info_image', models.ImageField(default='default_small_info.jpg', upload_to='desert_camp/')),
                ('second_section_title', models.CharField(default='Luxury Desert camp', max_length=255)),
                ('second_section_text', models.TextField(default='At Discover Morocco Tours, we specialize in organizing exceptional tours across Morocco.')),
                ('second_section_image', models.ImageField(default='default_image3.jpg', upload_to='desert_camp/')),
            ],
        ),
    ]
