# Generated by Django 5.0.8 on 2024-11-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Home - Discover Morocco Tours', max_length=255)),
                ('meta_description', models.TextField(default='Discover the beauty of Morocco with our exceptional tours and day trips. Contact us to plan your adventure today!')),
                ('meta_keywords', models.TextField(default='Morocco tours, day trips, desert tours, photography, luxury desert camp, Morocco travel')),
                ('hero_title', models.CharField(default='Our Gallery', max_length=255)),
                ('hero_paragraph', models.TextField(default='Create unforgettable memories with our services.')),
                ('hero_image', models.ImageField(default='default_hero.jpg', upload_to='gallery/')),
                ('gallery_section_title', models.CharField(default='Stunning Morocco Tours', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('gallery_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.gallerypage')),
            ],
        ),
    ]
