# Generated by Django 5.0.8 on 2024-11-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_gallerypage_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Home - Discover Morocco Tours', max_length=255)),
                ('meta_description', models.TextField(default='Discover the beauty of Morocco with our exceptional tours and day trips. Contact us to plan your adventure today!')),
                ('meta_keywords', models.TextField(default='Morocco tours, day trips, desert tours, photography, luxury desert camp, Morocco travel')),
                ('blog_title', models.CharField(default='A Taste of Morocco: Ultimate Food Guide', max_length=255)),
                ('posted_date', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=300)),
                ('author_name', models.CharField(default='Mohammed Travel Guide', max_length=255)),
                ('hero_image', models.ImageField(default='default_hero.jpg', upload_to='blog/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('related_title_tour', models.CharField(default='Experience Authentic Moroccan Cuisine', max_length=255)),
                ('related_description_tour', models.TextField(default='Insert marketing description')),
                ('link', models.CharField(default='www ...', max_length=255)),
                ('button_text', models.CharField(default='Read more', max_length=255)),
                ('category', models.CharField(default='Culture', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('title', 'Title'), ('section_title', 'Section Title')], max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='blog_content/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='user.blogpage')),
            ],
        ),
    ]
