# Generated by Django 5.0.8 on 2024-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_rename_blogpage_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontentblock',
            old_name='blog_page',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='related_description_tour',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='related_title_tour',
        ),
        migrations.RemoveField(
            model_name='blogcontentblock',
            name='content_type',
        ),
        migrations.AddField(
            model_name='blogcontentblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(default='Discover the beauty of Morocco...'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_keywords',
            field=models.TextField(default='Morocco tours, day trips, desert tours...'),
        ),
    ]
