# Generated by Django 5.0.8 on 2024-11-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_rename_blog_page_blogcontentblock_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='button_link',
            field=models.URLField(default='https://example.com/tour', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='button_text',
            field=models.CharField(default='Read More', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='related_paragraph',
            field=models.TextField(default='You can enjoy this in our tour where we explore the authentic tastes of Morocco.'),
        ),
        migrations.AddField(
            model_name='blog',
            name='related_title',
            field=models.CharField(default='Experience Authentic Moroccan Cuisine', max_length=255),
        ),
    ]
