# Generated by Django 5.0.8 on 2024-11-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(default='Discover the beauty of Morocco...'),
        ),
    ]
