# Generated by Django 5.0.8 on 2024-11-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_blog_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Enter contact email address', max_length=254)),
                ('location', models.CharField(help_text='Enter physical location or address', max_length=255)),
            ],
        ),
    ]
