# Generated by Django 5.0.8 on 2024-11-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tripadvisor_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='tripadvisor_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
