# Generated by Django 5.0.8 on 2024-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_contact_facebook_active_contact_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The FAQ question.', max_length=255)),
                ('answer_title', models.CharField(help_text='Title of the answer.', max_length=255)),
                ('answer_items', models.TextField(help_text='List items of the answer. Use new lines to separate items.')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tripadvisor_active',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tripadvisor_url',
        ),
    ]
