# Generated by Django 5.0.8 on 2024-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_faq_remove_contact_tripadvisor_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mobile_hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='homepage/'),
        ),
    ]
