# Generated by Django 5.0.8 on 2024-11-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_homepage_mobile_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='mobile_hero_image',
        ),
    ]
