# Generated by Django 5.0.8 on 2024-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_remove_homepage_mobile_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mobile_hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='homepage/'),
        ),
    ]
