# Generated by Django 5.0.8 on 2024-11-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_homepage_mobile_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='wechat_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='wechat_url_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatssap_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatssap_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
