# Generated by Django 5.0.8 on 2024-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_contact_wechat_url_contact_wechat_url_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my Site map', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Put your site map here:')),
            ],
        ),
    ]
