# Generated by Django 5.0.8 on 2024-11-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_sitemapentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='day',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='photographerdaydetail',
            name='photographer_tour',
        ),
        migrations.DeleteModel(
            name='PhotographerImage',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='PhotographerDayDetail',
        ),
    ]
