# Generated by Django 5.0.8 on 2024-11-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_remove_photographer_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographertourpage',
            name='image',
            field=models.ImageField(default='default_small_hero.jpg', upload_to='photographer_tours/'),
        ),
        migrations.AddField(
            model_name='photographertourpage',
            name='paragraphs',
            field=models.TextField(default='At Discover Morocco Tours, we specialize in organizing exceptional tours across Morocco...'),
        ),
        migrations.AddField(
            model_name='photographertourpage',
            name='section_title',
            field=models.CharField(default='Choose Your Destination, Let Us Do The Rest', max_length=255),
        ),
    ]
