# Generated by Django 5.0.8 on 2024-11-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_photographertourpage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='old_price',
            field=models.IntegerField(blank=True, help_text='Old Price', null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='price',
            field=models.IntegerField(blank=True, help_text='Price', null=True),
        ),
    ]
