# Generated by Django 5.0.8 on 2024-11-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_camp_old_price_camp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='old_price',
            field=models.IntegerField(blank=True, help_text='Price', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='Detailed tour description for users'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(blank=True, help_text='Price', null=True),
        ),
    ]
