# Generated by Django 5.0.8 on 2024-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_tour_old_price_alter_tour_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='excluded',
            field=models.TextField(blank=True, help_text='Please each excluded item on a new line.', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='prices',
            field=models.TextField(blank=True, help_text='Please each price on a new line.', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True, help_text='Please each included item on a new line.', null=True),
        ),
    ]
