# Generated by Django 5.0.8 on 2024-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_remove_tour_old_price_remove_tour_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytrip',
            name='price',
        ),
        migrations.AddField(
            model_name='daytrip',
            name='exluded',
            field=models.TextField(blank=True, help_text='Each included item on a new line.', null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='prices',
            field=models.TextField(blank=True, help_text='Please each price on a new line.', null=True),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='included',
            field=models.TextField(blank=True, help_text='Each included item on a new line.', null=True),
        ),
    ]
