# Generated by Django 5.0.8 on 2024-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_remove_daytrip_price_daytrip_exluded_daytrip_prices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_title', models.IntegerField(help_text='Title of the pop')),
                ('image', models.ImageField(help_text='Image for the pop', upload_to='tours/gallery/')),
                ('link', models.CharField(help_text='link', max_length=255)),
                ('description', models.TextField(help_text='brief description')),
            ],
        ),
    ]
