# Generated by Django 5.0.8 on 2024-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_pop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark the pop as active'),
        ),
    ]
