# Generated by Django 5.0.8 on 2024-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_pop_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='pop_title',
            field=models.CharField(help_text='Title of the pop', max_length=255),
        ),
    ]
