# Generated by Django 5.0.8 on 2024-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_pop_pop_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiondetail',
            options={'verbose_name': 'Day trips Actions', 'verbose_name_plural': 'C- Day Trip actions'},
        ),
        migrations.AlterModelOptions(
            name='camp',
            options={'verbose_name': 'Camp', 'verbose_name_plural': 'D- Camp'},
        ),
        migrations.AlterModelOptions(
            name='daydetail',
            options={'verbose_name': 'Tour Day', 'verbose_name_plural': 'B- Days for Tour'},
        ),
        migrations.AlterModelOptions(
            name='daytrip',
            options={'verbose_name': 'Day Trip', 'verbose_name_plural': 'C- Day Trip'},
        ),
        migrations.AlterModelOptions(
            name='daytripimage',
            options={'verbose_name': 'Day trips gallery', 'verbose_name_plural': 'C- Day Trip galleries'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page', 'verbose_name_plural': 'A- Home Page'},
        ),
        migrations.AlterModelOptions(
            name='pop',
            options={'verbose_name': 'POP', 'verbose_name_plural': 'Marketing POP'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'B- All Tours'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Tour gallery image', 'verbose_name_plural': 'B- Gallery for Tour'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='photoshoots_section_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_photoshoots_section',
        ),
        migrations.AlterField(
            model_name='actiondetail',
            name='title',
            field=models.CharField(help_text='Marketing title action', max_length=255),
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.TextField(help_text='Maeketing Camp description'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='dining_image',
            field=models.ImageField(help_text='Background image for the dining section', upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='experience_1_image',
            field=models.ImageField(help_text='Image for experience 1', upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='experience_2_image',
            field=models.ImageField(help_text='Image for experience 2', upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='experience_3_image',
            field=models.ImageField(help_text='Image for experience 3', upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='hero_image',
            field=models.ImageField(help_text='An image for header of the Camp', upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta description (between 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='meta_title',
            field=models.CharField(help_text='SEO Camp Title (between 50 to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(help_text='Marketing Camp Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='camp',
            name='suite_description',
            field=models.TextField(help_text=' Marekting Description Suite'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='suite_image',
            field=models.ImageField(help_text='Image of the suite', upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='suite_name',
            field=models.CharField(help_text='Marekting name Suite', max_length=100),
        ),
        migrations.AlterField(
            model_name='daydetail',
            name='day_number',
            field=models.IntegerField(help_text='Day order Day(1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='daydetail',
            name='title',
            field=models.CharField(help_text='Marketing Title day ', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='bigger_image',
            field=models.ImageField(help_text='Bigger image for the day trip', upload_to='daytrips/'),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='description',
            field=models.TextField(help_text='Marketing day trip description'),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (between 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='meta_title',
            field=models.CharField(help_text='SEO title day trip (between 50 to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='name',
            field=models.CharField(help_text='Marketing day trip for user', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the day trip title', unique=True),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='small_image',
            field=models.ImageField(help_text='Small image for the day trip', upload_to='daytrips/'),
        ),
        migrations.AlterField(
            model_name='daytripimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt image', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripimage',
            name='image',
            field=models.ImageField(help_text='Day trips images galleries', upload_to='daytrips/galleries/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(default='default_about.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_paragraph',
            field=models.TextField(help_text='Description About us, for each paragraph in new line'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(help_text='Title for about us section, be creative', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='comfort_image',
            field=models.ImageField(default='default_comfort.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='comfort_paragraph',
            field=models.TextField(default='Answer to question using small paragraphs'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='comfort_title',
            field=models.CharField(help_text='Why client chouse you title?', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='excursions_section_title',
            field=models.CharField(help_text='Title for Day Trips Section', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_button_text',
            field=models.CharField(help_text='Content of your button', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(help_text='An image for header of the page', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (50 up to 60 characters)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mobile_hero_image',
            field=models.ImageField(help_text='image For mobile', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tours_section_title',
            field=models.CharField(help_text='Title for Tour Section', max_length=255),
        ),
        migrations.AlterField(
            model_name='pop',
            name='image',
            field=models.ImageField(help_text='Image for the pop', upload_to='Global/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='bigger_image',
            field=models.ImageField(help_text='Bigger image for the tour(1300x680h)', upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='Marketing Tour Description'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (between 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_title',
            field=models.CharField(help_text='SEO title for the tour (between 50 to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(help_text='Marketing Tour Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the tour title', unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='small_image',
            field=models.ImageField(help_text='Small image for the tour(300w x 200H)', upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text image description', max_length=255),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(help_text='Gallery image', upload_to='tours/galleries/'),
        ),
    ]
