# Generated by Django 5.0.8 on 2024-11-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_actiondetail_options_alter_camp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'A- About us page'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'E- Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog page', 'verbose_name_plural': 'A- Blogs Page'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact info', 'verbose_name_plural': 'Z- Contact info'},
        ),
        migrations.AlterModelOptions(
            name='daytripspage',
            options={'verbose_name': 'Day Trips page', 'verbose_name_plural': 'A- Day Trips Page'},
        ),
        migrations.AlterModelOptions(
            name='desertcamppage',
            options={'verbose_name': 'Camps Page', 'verbose_name_plural': 'A- Camps page'},
        ),
        migrations.AlterModelOptions(
            name='gallerypage',
            options={'verbose_name': 'Gallery Page', 'verbose_name_plural': 'A- Gallery page'},
        ),
        migrations.AlterModelOptions(
            name='moroccotourspage',
            options={'verbose_name': 'Morocco Tours Page', 'verbose_name_plural': 'A- Morocco Tours Page'},
        ),
        migrations.AlterModelOptions(
            name='photographertourpage',
            options={'verbose_name': 'Photography Page', 'verbose_name_plural': 'A- Photography page'},
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='photographertourpage',
            name='destination_paragraphs',
        ),
        migrations.RemoveField(
            model_name='photographertourpage',
            name='destination_section_title',
        ),
        migrations.RemoveField(
            model_name='photographertourpage',
            name='image_description',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hero_paragraph',
            field=models.TextField(blank=True, help_text='Marketing small paragraphs for users', null=True),
        ),
        migrations.AddField(
            model_name='desertcamppage',
            name='hero_button_text',
            field=models.CharField(default='Explore more', max_length=255),
        ),
        migrations.AddField(
            model_name='photographertourpage',
            name='Second_section',
            field=models.CharField(blank=True, help_text='Title of second section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photographertourpage',
            name='image_section',
            field=models.ImageField(blank=True, help_text='image for this section', null=True, upload_to='pages_images/'),
        ),
        migrations.AddField(
            model_name='photographertourpage',
            name='section_paragraphs',
            field=models.TextField(blank=True, help_text='Description markting for section', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='client_care_image',
            field=models.ImageField(default='default_client_care.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='first_section_image',
            field=models.ImageField(default='default_first_section.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='first_section_text',
            field=models.TextField(help_text='Marketing title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='first_section_title',
            field=models.CharField(default='Your Gateway to Morocco', help_text='Marketing title ', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='service_image1',
            field=models.ImageField(default='default_service1.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='service_image2',
            field=models.ImageField(default='default_service2.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='service_image3',
            field=models.ImageField(default='default_service3.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonial1_image',
            field=models.ImageField(default='default_testimonial1.jpg', upload_to='pages_images'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonial2_image',
            field=models.ImageField(default='default_testimonial2.jpg', upload_to='pages_images'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonial3_image',
            field=models.ImageField(default='default_testimonial3.jpg', upload_to='pages_images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default='By Mohammed', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(default='Description of the blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='Blog title Marketing', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='button_link',
            field=models.URLField(default='Link here like: https://example.com/tour', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Write a category of your blog', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='related_paragraph',
            field=models.TextField(default='Desciption for you related tour marketing'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='related_title',
            field=models.CharField(default='Related Tour Title marketing', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcontentblock',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blogcontentblock',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the blog', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='all_day_trips_title',
            field=models.CharField(help_text='Title All Private Excursions and Day Trips', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='best_day_trips_title',
            field=models.CharField(help_text='Title for the best day trip section', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='blog_image',
            field=models.ImageField(help_text='Imgae for your section', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='blog_paragraph',
            field=models.TextField(default='Section Marekting title'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='blog_title',
            field=models.CharField(help_text='Section Marekting title', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='hero_button_text',
            field=models.CharField(help_text='Content of your button', max_length=50),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='hero_image',
            field=models.ImageField(help_text='An image for header of the page', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='service_image1',
            field=models.ImageField(help_text='Icon', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='service_image2',
            field=models.ImageField(help_text='Icon', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='service_image3',
            field=models.ImageField(help_text='Icon', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='service_title1',
            field=models.CharField(help_text='Licensed Guides', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='service_title2',
            field=models.CharField(help_text='Guided Walking Tour', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='service_title3',
            field=models.CharField(help_text='Flexible Rescheduling', max_length=255),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='unique_experiences_image',
            field=models.ImageField(help_text='image for your section', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='unique_experiences_paragraph',
            field=models.TextField(help_text='Marketing descriptions for your section'),
        ),
        migrations.AlterField(
            model_name='daytripspage',
            name='unique_experiences_title',
            field=models.CharField(help_text='Second Section Marekting title', max_length=255),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='first_section_image',
            field=models.ImageField(default='default_image2.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='second_section_image',
            field=models.ImageField(default='default_image3.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='desertcamppage',
            name='small_info_image',
            field=models.ImageField(default='default_small_info.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='hero_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='hero_button_text',
            field=models.CharField(help_text='Content of your button', max_length=50),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='hero_image',
            field=models.ImageField(help_text='An image for header of the page', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='service_image1',
            field=models.ImageField(default='default_service1.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='service_image2',
            field=models.ImageField(default='default_service2.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='service_image3',
            field=models.ImageField(default='default_service3.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='steps_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='strength_image1',
            field=models.ImageField(default='default_strength1.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='strength_image2',
            field=models.ImageField(default='default_strength2.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='strength_image3',
            field=models.ImageField(default='default_strength3.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='strength_image4',
            field=models.ImageField(default='default_strength4.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='strength_image5',
            field=models.ImageField(default='default_strength5.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='strength_image6',
            field=models.ImageField(default='default_strength6.jpg', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='moroccotourspage',
            name='why_choose_image',
            field=models.ImageField(default='default_hero.jpg', upload_to='pages_images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_price',
            field=models.PositiveIntegerField(help_text='Current price of the Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(help_text='Duration of the Package, like 2h', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='old_price',
            field=models.PositiveIntegerField(help_text='Old price of the Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photographer_tour_page',
            field=models.ForeignKey(help_text='Choose photography page', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='user.photographertourpage'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(help_text='Title of the Package', max_length=100),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='hero_button_text',
            field=models.CharField(help_text='Content of your button', max_length=50),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='hero_image_large',
            field=models.ImageField(help_text='Image for desktop', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='hero_image_medium',
            field=models.ImageField(help_text='Image Medium', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='hero_image_small',
            field=models.ImageField(help_text='Small image', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='hero_paragraph',
            field=models.TextField(help_text='Marketing small paragraphs for users'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='hero_title',
            field=models.CharField(help_text='Marketing Title for users', max_length=255),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='image',
            field=models.ImageField(help_text='image for this section', upload_to='pages_images/'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='meta_description',
            field=models.TextField(help_text='Description of the page (150 up to 160 characters)'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='meta_keywords',
            field=models.TextField(help_text='Keywords'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='meta_title',
            field=models.CharField(help_text='Title of the page (50 up to 60 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='package_section_title',
            field=models.CharField(help_text='Section Package Photography Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='paragraphs',
            field=models.TextField(help_text='Marketing Description fpr same section'),
        ),
        migrations.AlterField(
            model_name='photographertourpage',
            name='section_title',
            field=models.CharField(help_text='Marketing title for section', max_length=255),
        ),
    ]
